import base64
import hashlib
import json
import os
import secrets
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row
from flask import Flask, jsonify, request
from cryptography.hazmat.primitives import serialization

app = Flask(__name__)

LICENSE_DATABASE_URL = os.getenv("LICENSE_DATABASE_URL", "").strip()
ADMIN_KEY = os.getenv("LICENSE_ADMIN_KEY", "test-admin-key")


def connect():
    if not LICENSE_DATABASE_URL:
        raise RuntimeError("LICENSE_DATABASE_URL is not configured.")

    # Parse the Supabase URI ourselves so unsupported URI options such as
    # pgbouncer never reach psycopg 3.
    from urllib.parse import unquote, urlsplit

    raw_url = LICENSE_DATABASE_URL.strip().strip('"').strip("'")
    if raw_url.startswith("LICENSE_DATABASE_URL=") or raw_url.startswith("DATABASE_URL="):
        raw_url = raw_url.split("=", 1)[1].strip().strip('"').strip("'")
    parts = urlsplit(raw_url)
    if not (parts.scheme.startswith("postgresql") or parts.scheme == "postgres"):
        raise RuntimeError("LICENSE_DATABASE_URL must be a PostgreSQL connection URL.")
    if not parts.hostname:
        raise RuntimeError("LICENSE_DATABASE_URL is missing the database host.")
    if not parts.username:
        raise RuntimeError("LICENSE_DATABASE_URL is missing the database username.")
    if not parts.password:
        raise RuntimeError("LICENSE_DATABASE_URL is missing the database password.")

    return psycopg.connect(
        host=parts.hostname,
        port=parts.port or 5432,
        dbname=parts.path.lstrip("/") or "postgres",
        user=unquote(parts.username),
        password=unquote(parts.password),
        sslmode="require",
        row_factory=dict_row,
    )


def init_db():
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS licenses (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    license_hash TEXT UNIQUE NOT NULL,
                    customer_name TEXT NOT NULL,
                    max_devices INTEGER NOT NULL DEFAULT 1,
                    status TEXT NOT NULL DEFAULT 'active',
                    expires_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                CREATE TABLE IF NOT EXISTS devices (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    license_id BIGINT NOT NULL REFERENCES licenses(id) ON DELETE CASCADE,
                    device_id TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (license_id, device_id)
                );

                CREATE INDEX IF NOT EXISTS idx_devices_license_id
                    ON devices(license_id);

                CREATE INDEX IF NOT EXISTS idx_licenses_status
                    ON licenses(status);
            """)
        conn.commit()


def key_hash(value):
    return hashlib.sha256(value.strip().encode("utf-8")).hexdigest()


def load_private_key():
    pem = os.getenv("LICENSE_PRIVATE_KEY_PEM", "").replace("\\n", "\n").strip()
    if not pem:
        raise RuntimeError("LICENSE_PRIVATE_KEY_PEM is not configured.")
    return serialization.load_pem_private_key(pem.encode("utf-8"), password=None)


def make_token(license_row, device_id, app_version):
    payload = {
        "license_id": license_row["id"],
        "customer_name": license_row["customer_name"],
        "device_id": device_id,
        "app_version": app_version or "1.0.0",
        "status": "active",
        "issued_at": datetime.now(timezone.utc).isoformat(),
    }
    encoded = base64.urlsafe_b64encode(
        json.dumps(payload, separators=(",", ":"), sort_keys=True).encode()
    ).rstrip(b"=").decode()
    signature = load_private_key().sign(encoded.encode())
    sig = base64.urlsafe_b64encode(signature).rstrip(b"=").decode()
    return f"{encoded}.{sig}"


@app.post("/admin/create")
def create_license():
    if request.headers.get("X-License-Admin-Key", "") != ADMIN_KEY:
        return jsonify(success=False, message="Unauthorized"), 401

    data = request.get_json(silent=True) or {}
    customer_name = str(data.get("customer_name", "")).strip()
    try:
        max_devices = int(data.get("max_devices", 1) or 1)
    except (TypeError, ValueError):
        return jsonify(success=False, message="max_devices must be an integer"), 400

    if not customer_name:
        return jsonify(success=False, message="customer_name is required"), 400
    if max_devices < 1:
        return jsonify(success=False, message="max_devices must be at least 1"), 400

    license_key = "FIN-" + secrets.token_hex(9).upper()
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """INSERT INTO licenses
                   (license_hash, customer_name, max_devices, status, created_at)
                   VALUES (%s, %s, %s, 'active', %s)
                   RETURNING id""",
                (key_hash(license_key), customer_name, max_devices, datetime.now(timezone.utc)),
            )
            license_id = cur.fetchone()["id"]
        conn.commit()

    return jsonify(
        success=True,
        license_id=license_id,
        license_key=license_key,
        customer_name=customer_name,
        max_devices=max_devices,
    ), 201


@app.post("/api/license/activate")
def activate():
    data = request.get_json(silent=True) or {}
    license_key = str(data.get("license_key", "")).strip()
    device_id = str(data.get("device_id", "")).strip()
    app_version = str(data.get("app_version", "1.0.0")).strip()

    if not license_key or not device_id:
        return jsonify(success=False, message="License key and device ID are required"), 400

    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM licenses WHERE license_hash = %s",
                (key_hash(license_key),),
            )
            row = cur.fetchone()

            if not row:
                return jsonify(success=False, message="Invalid license key"), 403
            if row["status"] != "active":
                return jsonify(success=False, message="License is not active"), 403

            cur.execute(
                "SELECT * FROM devices WHERE license_id = %s AND device_id = %s",
                (row["id"], device_id),
            )
            device = cur.fetchone()

            if not device:
                cur.execute(
                    "SELECT COUNT(*) AS count FROM devices WHERE license_id = %s",
                    (row["id"],),
                )
                count = cur.fetchone()["count"]

                if count >= row["max_devices"]:
                    return jsonify(
                        success=False,
                        message="This license has reached its device limit",
                    ), 403

                cur.execute(
                    """INSERT INTO devices
                       (license_id, device_id, created_at, last_seen)
                       VALUES (%s, %s, %s, %s)""",
                    (
                        row["id"],
                        device_id,
                        datetime.now(timezone.utc),
                        datetime.now(timezone.utc),
                    ),
                )
            else:
                cur.execute(
                    "UPDATE devices SET last_seen = %s WHERE id = %s",
                    (datetime.now(timezone.utc), device["id"]),
                )

        conn.commit()

    token = make_token(row, device_id, app_version)
    return jsonify(
        success=True,
        message=f"License activated for {row['customer_name']}",
        activation_token=token,
    )


@app.get("/health")
def health():
    try:
        with connect() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT 1")
                cur.fetchone()
        return jsonify(status="ok", database="connected")
    except Exception:
        return jsonify(status="error", database="unavailable"), 503


try:
    init_db()
except Exception:
    app.logger.exception("License database initialization failed during startup")

import admin_panel  # register web admin routes

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "5050")), debug=False)
